# Site settings
title: leetcode2017
baseurl: "/leetcode"
url: "https://leetcoder2017.github.io"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave blank to disable it
google_analytics: 
disqus_shortname: 
